# Generated by Django 6.0.7 on 2026-09-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_location_alter_meetup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetups.location'),
        ),
    ]
