# Generated by Django 6.0.7 on 2026-09-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_alter_meetup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.CharField(),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
